version: "3.9"

services:
  db:
    image: postgres:16
    container_name: inventario_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventario_sophyfarm
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - inventario_net

  backend:
    build: .
    container_name: inventario_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/inventario_sophyfarm
      FLASK_ENV: development
      FLASK_APP: run.py
    ports:
      - "5000:5000"
    networks:
      - inventario_net

networks:
  inventario_net:

volumes:
  dbdata:
